version: '3.1'

services:
  db:
   image: postgres
   restart: always
   environment:
     - POSTGRES_USER=site
     - POSTGRES_PASSWORD=site123
     - POSTGRES_DB=site
   volumes:
     - /home/ks/docker-project/volumes/db:/var/lib/postgresql/data
   ports:
     - ${POSGRES_PORT:-5432}:5432
#-----------------WebApp Container--------------------------------------#
  nodejs:
   build: 
    context: .
    dockerfile: Dockerfile
   image: nodejs
   container_name: nodejs
   restart: always
   ports:
    - "3000:3000"
#-----------------ReverseProxy--------------------------------------#
  reverse-proxy:
    image: nginx
    restart: always
    ports:
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
